server {
    listen 80;
    server_name _;
    resolver 127.0.0.11 valid=10s ipv6=off;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    location = /api {
        return 301 /api/;
    }

    location /api/ {
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_pass http://server_service:8000/;
    }

    location /storage/ {
        rewrite ^/storage(/.*)$ $1 break;

        proxy_set_header Host minio:9000;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;

        proxy_pass http://minio:9000;
    }

    location /rag/ {
        rewrite ^/rag(/.*)$ $1 break;

        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_pass http://rag-service:8000;
    }

    location / {
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_pass http://server_service:8000/;
    }

}
