DOCUMENT_STATUS_UPLOADED = "uploaded"
DOCUMENT_STATUS_PROCESSING = "processing"
DOCUMENT_STATUS_PROCESSED = "processed"
DOCUMENT_STATUS_INDEXING = "indexing"
DOCUMENT_STATUS_INDEXED = "indexed"
DOCUMENT_STATUS_COMPLETED = "completed"
DOCUMENT_STATUS_FAILED = "failed"
DOCUMENT_STATUS_CANCELLED = "cancelled"

DOCUMENT_INDEXED_STATUSES = [
    DOCUMENT_STATUS_INDEXED,
    DOCUMENT_STATUS_COMPLETED,
]

PIPELINE_STAGE_UPLOAD = "upload"
PIPELINE_STAGE_PARSING = "parsing"
PIPELINE_STAGE_CHUNKING = "chunking"
PIPELINE_STAGE_INDEXING = "indexing"
PIPELINE_STAGE_GRAPH = "graph"
PIPELINE_STAGE_INGEST = "ingest"
